### ISSUE TITLE
KeyError: 'aprice' when running `lots list`

### ISSUE THREAD

**Issue by brianjp93** [edkedk99/hledger-lots#4]
After upgrading from 1.32.3 -> 1.33.1 I am getting this error while trying to run many `hledger lots` commands.

It seems like the output format of `hledger print --output-format=json` has changed and `aprice` no longer exists in the dictionary.

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/bin/hledger-lots", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/__main__.py", line 5, in main
    cli(obj=dict())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/cli.py", line 206, in list_commodities
    table = lots_info.infos_table("plain")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/fifo_info.py", line 106, in infos_table
    return self.get_infos_table(self.infos, output_format)
                                ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/fifo_info.py", line 101, in infos
    infos = [self.get_info(com) for com in self.commodities]
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/fifo_info.py", line 89, in get_info
    txns = hledger2txn(self.journals, commodity, self.no_desc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ledger/lib/python3.12/site-packages/hledger_lots/hl.py", line 46, in hledger2txn
    if prices_items["acommodity"].upper() == cur.upper() and prices_items["aprice"]
                                                             ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'aprice'
```

**Comment by brianjp93** [comment]
It seems this was just a rename to `acost`
https://github.com/simonmichael/hledger/commit/323f87b3e96f415c4484ea930262b64d4b12b41f

**Comment by Admin661** [comment]
Is the issue resolved yet? You'll have to rectify with the ledger loptimal weblink and try it again.
